New README figure
andreped/super-ml-pets pull request #47
Opened 2023-03-31 19:32 UTC by jpdefrutos

First draft of the README figure

2023-03-31 20:02 UTC, andreped commented
Wow! This is fantastic! Love it!

2023-03-31 20:03 UTC, andreped requested changes

2023-03-31 20:03 UTC, andreped commented on assets/SMLP.svg
Would be great if you could move the brains a little closer, such that the figure itself is more compact.

2023-04-01 08:18 UTC, jpdefrutos commented on assets/SMLP.svg
Uploaded new figure in https://github.com/andreped/super-ml-pets/pull/47/commits/09d1a5ddd3765250c624c9d9a87d2921904cbdb6

2023-04-01 08:18 UTC, jpdefrutos commented
Uploaded new figure in https://github.com/andreped/super-ml-pets/pull/47/commits/09d1a5ddd3765250c624c9d9a87d2921904cbdb6

2023-04-01 08:59 UTC, andreped approved these changes
LGTM. Great job!

2023-04-01 08:59 UTC, merged